### PR TITLE
Scoreboard

### PR DESCRIPTION
**Pull request by Rednaxela700**
minor fixes

### CODE REVIEW

**Comment by michal-kusnierz** [comment]
on second thought... 
- clearBtn works (clears localStorage), but when you add a playername you get your (deleted!) array rendered back.
- the other thing is that if you enter the same playername again, you get all of this player scores bolded (don't know if we want it that way)

**Comment by Rednaxela700** [comment]
we should pick bolded/actual player by name and date

**Comment by michal-kusnierz** [comment]
yup. or just date

**Comment by michal-kusnierz** [comment]
I moved clearBtn. 
- now we have 'top 10' btn instead. 
- clearBtn is rendered after sb views top 10

**Comment by michal-kusnierz** [comment]
changes:
- 'top10' btn renders only if there are any scores stored
- new heading in modal with highscores: "najlepsze wyniki:"
- I've hidden highest score→should be taken as the highest value from gameScores arr (lastScore overwrites it after resetScore)

**Pull request merged**
